#!/bin/sh

# Prints the current mic level.
src=$(pamixer --list-sources | grep -iE '"built-in Audio Analog stereo"' | awk '{print $1}')
case $BLOCK_BUTTON in
  1) pavucontrol ;;
  2) pamixer --source $src -t ;;
  4) pamixer --source $src -i 1 ;;
  5) pamixer --source $src -d 1 ;;
esac

[ $(pamixer --source $src --get-mute) = true ] && echo "󰩅 " && exit

mic="$(pamixer --source $src --get-volume)"

echo "󰍮:$mic%"
