#!/bin/sh

# Prints the current mic level.

case $BLOCK_BUTTON in
  1) pavucontrol ;;
  2) pamixer --source 1 -t ;;
  4) pamixer --source 1 -i 1 ;;
  5) pamixer --source 1 -d 1 ;;
esac

[ $(pamixer --source 1 --get-mute) = true ] && echo "" && exit

mic="$(pamixer --source 1 --get-volume)"

echo ":$mic%"
